version: "3.7"
services:
  db:
    image: "mysql:5.7"
    container_name: mysql_db
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
        - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    logging:
            driver: none
    ports:
      - "33061:3306"
  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
            driver: none
  app:
    image: budget_image
    container_name: budget_app
    command: bash -c "bundle && bundle exec rake db:create db:migrate && bundle exec rails s -p 3000 -e development -b '0.0.0.0'"
    environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_PORT: 3306
     DB_HOST: mysql_db
     RAILS_ENV: development
     RAILS_MAX_THREADS: 5
     REDIS_HOST: redis
     REDIS_PORT: 6379
    volumes:
      - ../budget:/budget
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"
volumes:
  db:
  bundle:
  redis: