version: "3.7"
services:
  db:
    image: "mysql:5.7"
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
        - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    ports:
      - "3306:3306"
  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
volumes:
  db:
  redis: